id: PBB7CC8CC
initial_creation_type: ocr
source_metadata:
  volumes:
    477cba122f3b4e239e043bda1141ae5c:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་ཐ་མ།
      total_pages: 1902
      volume_number: 64
