id: PBB7CC8CC
initial_creation_type: ocr
source_metadata:
  volumes:
    d1b9df8d58ec447eaa140c87898f01f8:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་ཐ་མ།
      total_pages: 1902
      volume_number: 64
